### ISSUE TITLE
Issue updating auth0_connection (created by earlier tf-auth0-provider)

### ISSUE THREAD

**Issue by arevenes** [alexkappa/terraform-provider-auth0#402] opened 2021-05-25 10:18 UTC
### Description
Fails terraforming Auth0, potentially because of some issue updating resource auth0_connection after TF upgrade. This happened after upgrading TF from 12 -> 13 and bumping terraform-provider-auth0 from older version. Let me know if more output is required.

### Terraform Version
0.13.7

Terraform 0.13.17
terraform-provider-auth0_v0.21.0 - alexkappa/auth0

### Affected Resource(s)

auth0_connection (but whole deployment fails)

### Terraform Configuration Files

```hcl
resource "auth0_connection" "rest-api-fallback" {
  name = "rest-api-fallback"
  strategy = "auth0"
  is_domain_connection = false
  enabled_clients = [auth0_client.vcc.client_id, var.auth0-api-explorer-client-id]
  options {
    requires_username = false
    password_policy = "good"
    disable_signup = true
    import_mode = true
    brute_force_protection = true
    enabled_database_customization = true
    non_persistent_attrs = ["no_error"]
    custom_scripts = {
      get_user = file("${path.module}/connections/get_user.js")
      login = file("${path.module}/connections/login.js")
    }
    configuration = {
      rest_api_endpoint = var.rest-api-endpoint
      legacy_tenant = var.legacy-tenant
    }
  }
}

```

### Expected Behavior
It should successfully deploy

### Actual Behavior
It fails to deploy with a stacktrace

### Steps to Reproduce
1. `terraform apply`

### Debug Output
https://gist.github.com/arevenes/9bad60897af8507cc7f77976b787fe78

### Panic Output
panic: interface conversion: interface is nil, not interface {}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment] 2022-02-21 15:32
This seems to be a duplicate of https://github.com/alexkappa/terraform-provider-auth0/issues/364. Closing in favor of that.

**Closed by sergiught** 2022-02-21 15:32 UTC
