### ISSUE TITLE
Adding secrets after hook creation does not work

### ISSUE THREAD

**Issue by FlowFlorent** [alexkappa/terraform-provider-auth0#408] opened 2021-06-16 16:31 UTC
### Description

Hello!

As per the title mentions, adding secrets after hook creation does not seem to work. 

What has been tested:
Modifying an already setup secrets works:

```tf
secrets = {
      my_var        = "old_value" 
    }
```

 ```tf
secrets = {
      my_var        =  "new_value"
    }
```

Adding a secret to an existing hook does not:

```tf
secrets = {
      my_var        = "value" 
    }
```

```tf
secrets = {
      my_var                = "value" 
      my_new_var        = "value" 
    }
```

Output from our actual plan:

```
~ secrets      = (sensitive)
        # (4 unchanged attributes hidden)
```

### Terraform Version

```
Terraform `0.15.5`
provider.auth0 `0.21.0`
```

### Affected Resource(s)

* auth0_hook

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a [Github Gist](https://gist.github.com/) instead.
```

### Expected Behavior

Adding new secrets to an existing auth0_hook should work.

### Actual Behavior

Adding new secrets does nothing.

### Steps to Reproduce

1. Create an `auth0_hook` 
```tf
resource "auth0_hook" "my_hook" {
  name       = "my-hook"
  script     = file("${path.module}/hooks/hooks/post-user-registration/my-hook.js")
  trigger_id = "post-user-registration"
  enabled    = true
  secrets = {
      foo        = "foo"
    }
}
```
2. Plan and apply the changes
3. Make hook is deployed in auth0
4. Update `my_hook` by adding a new secret:
```tf
resource "auth0_hook" "my_hook" {
  name       = "my-hook"
  script     = file("${path.module}/hooks/hooks/post-user-registration/my-hook.js")
  trigger_id = "post-user-registration"
  enabled    = true
  secrets = {
      foo        = "foo"
      bar       = "bar"
    }
}
```
5. Plan and apply the changes
6. Notice that the new secret (`bar`) is not added in auth0

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mbelang** [comment] 2021-09-07 20:46
@alexkappa any idea what could cause this?

**Comment by alekc** [comment] 2021-09-19 17:34
Weird, I was not able to reproduce it, although it might be that it's because I am on a different Terraform sdk. 

I've run it through this test scenario: https://github.com/alekc/terraform-provider-auth0/pull/15 and it looks ok. 

Couple of things to keep an eye on:

- Atm current implementation in this repo doesn't check which secrets do exist remotely during the read phase (https://github.com/alexkappa/terraform-provider-auth0/blob/534e1f833e369e72d338ee1f3448898dfa54c6fd/auth0/resource_auth0_hook.go#L89) , so if one of the secrets was deleted from the dashoboard ui it won't fix it until there is a change in terraform config
- Auth0 doesn't report back the secret value, but only secret keys, so you cannot ensure that the secrets on the auth0 were not changed. Actions at least do report back a last_updated field, so it was possible to leverage that to ensure that the secret was not changed.

**Comment by mbelang** [comment] 2021-09-22 00:16
@alekc Since you do not use the same provider, then it is highly possible it is workings in yours. It this a fork of @alexkappa or simply a rewrite? 

Honestly, the support here is a bit slow and the feedback loop is really slow as well. This provider is highly valuable to us.

**Comment by alekc** [comment] 2021-09-22 07:06
@mbelang it's a fork of the tip of this one (from version 0.21.0) + several layers of different new implementations. See the release notes / PR to see what have been changed.

**Comment by sergiught** [comment] 2022-02-21 18:00
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/40 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.

**Closed** 2022-02-21 18:00 UTC
